### ISSUE TITLE
SLU17 - Interpretation confirmation

### ISSUE THREAD

**Issue by joaobcampos** [LDSSA/bootcamp#43]
In the last exercise where we explore learning curves we are confronted with the function 
```
learning_curve(estimator, X, y)
```

For example, if the `train_scores.shape` is `(7,8)`, the `7 `will correspond to a different ration `#number_of_training_samples/#number_of_test_samples` and the 8 will correspond to the number of experiences made for that ratio.

For each experiment the `#number_of_training_samples/#number_of_test_samples`  is the same but the actual samples used to build the training and test set are different. Is my understanding correct?

**Comment by hershaw** [comment]
Good question @joaobcampos!

You are correct in your understanding. Each "row" in the `train_scores` as well as the `test_scores` arrays correspond to the number of training samples you use for a particular point on the x-axis of the learning curve that we plot later on. Each "column" corresponds to a particular training/test split (dictated by a random number generator unless you use the `random_state` parameter) of the same size.

Does this make sense?

**Comment by joaobcampos** [comment]
Absolutely. Ty

**Comment by Juliana-R** [comment]
Closing this issue as it is now almost 2 years old. Feel free to reopen it.
