### ISSUE TITLE
importing matplotlib not checked in unit tests

### ISSUE THREAD

**Issue by echo66** [LDSSA/bootcamp#50]
We forgot to include an extra assert for ``matplotlib`` in order to check if the student imported ``matplotlib``.

**Comment by hershaw** [comment]
@echo66 is this blocking any student submissions or causing grades to be incorrect?

**Comment by PedroGFonseca** [comment]
@echo66 is this one worth  fixing?

**Comment by Juliana-R** [comment]
**Issue inactive for more than 1 year**, will be closed. Reopen if necessary.
