### ISSUE TITLE
SLU3, exercise 9

### ISSUE THREAD

**Issue by echo66** [LDSSA/bootcamp#53]
This issue is related to a concept called "natural order". In simple terms, it means that "list" (e.g. python list, pandas dataframe, ordered iterables, pandas series, etc) elements having the same sorting value (i.e. ties) will preserve the same list order that they had in the original list. In order to understand what I'm saying, let's look at the following example

Original list
```
id, val
1, 30
2, 11
3, 10
4, 91
5, 91
6, 91
7, 91
8, 32
9, 91
```

A sorting algorithm that preserves the natural order of elements will produce:
```
id, val
3, 10
2, 11
1, 30
8, 32
4, 91
5, 91
6, 91
7, 91
9, 91
```

On the other hand, a sorting algorithm that doesn't preserve natural order could have the following result
```
id, val
3, 10
2, 11
1, 30
8, 32
4, 91
7, 91
9, 91
5, 91
6, 91
```

When you read "stable" at [numpy sort docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.sort.html), they are talking about the natural order.

You might be asking "What is the better approach to sorting?". My response: the one that gives you the sorted data structure without changing stuff that shouldn't be changed.

**Comment by PedroGFonseca** [comment]
On Exercise 9, SLU3, the question reads as follows:
>  [...] find the least alcoholic beer per brewery. And then find the five breweries that have the least alcoholic beers.
>  The result should be a list with the brewery names.

To pass the grader, your answer needs to be _"result should be a list with the brewery names, from smallest to largest"_. In other words, your output list needs to be `[name of smallest, name of 2nd smallest, ... , name of 5th smallest, ]`

However, there are two breweries which are tied, and the grader expects `'Hopworks Urban Brewery'` to come before `'Evil Twin Brewing',`. There is also a tie for 5th place (but all implementations seem to get that one right by some miracle).  That's what has got a few people stuck, as both answers should be acceptable.

**Comment by orlandocosta76** [comment]
Hi, I read this and it was not clear which preferred sort method should be used for this question. 

Since I've just submitted my notebook for this unit, I can say the grader is not assuming preservation of natural order.

**Comment by Juliana-R** [comment]
**Issue inactive for more than 1 year**, will be closed. Reopen if necessary. @PedroGFonseca
