### ISSUE TITLE
SLU3,  Exercise 9

### ISSUE THREAD

**Issue by Rasmnev** [LDSSA/bootcamp#54]
In this exercise, inside the code Cell there is a comment stating 

` '# Group the breweries, get the average abv per brewery and get the top 5 least alcoholic ones`

But the question reads:

> [...] find the least alcoholic beer per brewery. And then find the five breweries that have the least alcoholic beers.  The result should be a list with the brewery names.

We are supposed to find the least alcoholic beer per brewery as the question states and ignore the comment about average abv

**Comment by PedroGFonseca** [comment]
The student and instructor versions seem to have diverged, correcting on the instructor version

**Comment by Juliana-R** [comment]
**Issue inactive for more than 1 year**, will be closed. Reopen if necessary. @hershaw
