### ISSUE TITLE
SLU10 Q6 - missing axis=1

### ISSUE THREAD

**Issue by pticao** [LDSSA/bootcamp#55]
![imagem](https://user-images.githubusercontent.com/14089724/40887211-f3c7cfe6-673c-11e8-8452-6a65b82fa4d3.png)

instead of:
X = data.drop('Class').values
shouldn't be?
X = data.drop('Class', axis=1).values****

**Comment by Juliana-R** [comment]
**Issue inactive for more than 1 year**, will be closed. Reopen if necessary. @PedroGFonseca
